### ISSUE TITLE
Create favicon for different devices

### ISSUE THREAD

**Issue by blackrabbit99** [fest-dev/fest-dev.github.io#7]
https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/

**Comment by LuisMMVieira** [comment]
![Image](https://user-images.githubusercontent.com/25463387/207461943-dcf50b0c-3156-41b4-9ff4-4135b665b1b2.png)
[favicon_devfest.zip](https://github.com/fest-dev/fest-dev.github.io/files/10222713/favicon_devfest.zip)
